# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: James Higgott
email: your-email@domain.com
description: James Higgott lives in London. He does charity/NFP digital stuff for a living and he can play the drums.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jiggott.com" # the base hostname & protocol for your site, e.g. http://example.com
socialimageurl: http://graphics8.nytimes.com/images/2012/02/19/us/19whitney-span/19whitney-span-articleLarge.jpg
twitter_username: jiggott
github_username: jiggott
timezone: Europe/London
permalink: /:year/:title

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
